name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  files-to-push:
    description: 'Files to push to the target branch'
    required: true
  source-branch:
    description: 'Source branch'
    required: true
  user-email:
    description: 'Email for the git commit'
    required: true
  user-name:
    description: 'Name for the git commit.'
    required: true
  repository:
    description: 'Repository name'
    required: true
  target-branch:
    description: 'Set target branch name.'
    required: true
  commit-message:
    description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
    default: 'Update from ORIGIN_COMMIT'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files-to-push }}
    - ${{ inputs.source-branch }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.repository }}
    - ${{ inputs.target-branch }}
    - ${{ inputs.commit-message }}
branding:
  icon: 'git-commit'
  color: 'green'
